version: '3.9'

services:
    php:
        container_name: noda_soft.php
        image: noda_soft:php
        build: .
        env_file: .env
        volumes:
            - ./:/var/www/html
        networks:
            noda_soft:
        ports:
            - "127.0.0.1:8002:80"

    db:
        container_name: noda_soft.db
        image: mysql:8
        env_file: .env
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes:
            - ./db-structure.sql:/docker-entrypoint-initdb.d/db-structure.sql
            - db_data:/var/lib/mysql
        networks:
            noda_soft:
        ports:
            - "127.0.0.1:3306:3306"

    pma:
        container_name: noda_soft.pma
        image: phpmyadmin
        networks:
            noda_soft:
        ports:
            - "127.0.0.1:8080:80"
        environment:
            PMA_ARBITRARY: 1
            PMA_USER: root
            PMA_PASSWORD: ${DB_ROOT_PASSWORD}

volumes:
    db_data:

networks:
    noda_soft: